- name: installing package
  hosts: all
  become: yes
  vars_files:
  - /home/ec2-user/credentials.yaml
  serial: 1
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present

  - name: starting and enabling nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes