  - name: install mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: installing PyMySQL using pip
    ansible.builtin.pip:
      name: PyMySQL
      state: present
      executable: pip3.9 

  - name: installing cryptography using pip
    ansible.builtin.pip:
      name: cryptography
      state: present
      executable: pip3.9

  - name: connect mysql server 
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
    ignore_errors: true
    register: mysql_info

  - name: check mysql info
    ansible.builtin.debug:
     msg: "{{ mysql_info }}"

  - name: setup password for mysql server
    ansible.builtin.command: "mysql_secure_installation --set--root-pass {{ mysql_root_password }}"
    when: mysql_info.failed is true
    
