- name: remove  a directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  ignore_errors: true

- name: create  a directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

# - name: download the code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component}}-v2.zip
#     dest: /tmp/backend.zip

- name: "unzip the  {{ component}} code"
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component}}-v2.zip" 
    dest: "{{ app_location }}"
    remote_src: yes  #by default ansible thinks this is in ansible server